name: Run Tests

on:
  push:
    branches: main
    paths-ignore:
      - "**/*.md"

  pull_request:
    branches: main
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod

      - name: Run Tests
        run: make test

      - name: Print Coverage
        run: make cover
