name: Validate Schema

on:
  push:
    branches: main
    paths-ignore:
      - "**/*.md"

  pull_request:
    branches: main
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod

      - name: Validate Schema
        run: make validate-schema
